# Generated by Django 3.2.2 on 2023-07-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_remito_remitoproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='codigo_proveedor',
            field=models.CharField(default='art-0001', max_length=50, verbose_name='Código de Proveedor'),
        ),
    ]
